# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Boulder DSA
email: boulderdsa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Boulder DSA is a local chapter of the Democratic Socialists of America,
    covering Boulder and Broomfield counties.  We find that unchecked capitalism
    has created a society that puts corporate profit above human rights, and we
    are committed to changing that through direct, grassroots action.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boulderdsa.org" # the base hostname & protocol for your site, e.g. http://example.com
author: Boulder DSA

# Build settings
markdown: kramdown

permalink: pretty

exclude:
    - CNAME
    - README.md

sass:
#    style: :compressed

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "css"
    values:  
      layout: null
  - scope:
      path: ""
      type: posts
    values:
      layout: newspost
      category: news
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      title_prefix: ""


# Site data
navlinks:
- title: About Us
  url: /about/
- title: News
  url: /news/
- title: Resources
  url: /resources/
- title: Calendar
  url: /calendar/
- title: CU YDSA
  url: /ydsa/
- title: Contact Us
  url: /contact/

socialmedia:
- name: facebook
  url: https://www.facebook.com/boulderdsa/
- name: twitter
  url: https://twitter.com/boulderDSA
- name: instagram
  url: #
- name: mastodon
  url: "#"
- name: diaspora
  url: "#"
